language: rust

env:
  global:
    - PROJECT_NAME=fie

matrix:
  include:
    - os: osx
      rust: nightly
      env: TARGET=x86_64-apple-darwin
      cache: cargo
    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu
      cache: cargo

sudo: false

script:
  - cargo test --features cli --target $TARGET

before_deploy:
  - cargo build --release --features cli --target $TARGET
  - zip "$PROJECT_NAME-$TRAVIS_TAG-$TARGET.zip" -j target/$TARGET/release/fie fie.toml

deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file_glob: true
  file: ${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}*
  # don't delete the artifacts from previous phases
  skip_cleanup: true
  overwrite: true
  # deploy when a new tag is pushed
  on:
    # channel to use to produce the release artifacts
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
