# Login and password from Gab.com
[api.gab]
username = "username"
password = "password"

# Login and password from Minds.com
[api.minds]
username = "username"
password = "password"

# Consumer Token of twitter app
[api.twitter.consumer]
key = "key"
secret = "secret"

# Authorization Token to access user account. Generated in developer page.
[api.twitter.access]
key = "key"
secret = "secret"

# Mastodon config
# You can use own application in Developement section
# and get access token
[api.mastodon]
host = "pawoo.net"
access_token = ""

# Configures which platforms to use by default.
# If this section is omitted then it is assumed that all to use.
# Otherwise missing platform means it is not used.
# Allowed values true/false
[platforms]
minds = true
gab = true
twitter = true
mastodon = true

[settings]
# Amount of seconds to wait for responses from API server.
# All request fails when it exceeds this time
# Default value is 5 seconds
timeout = 5
